name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: npm ci && npm test
      - name: Coverage
        run: npm run test:cov 
      - name: Verify Coverage
        run: |
          COVERAGE=$(node -pe "JSON.parse(require('fs').readFileSync('./coverage/coverage-summary.json')).total.lines.pct")
          if [ "$COVERAGE" -lt "80" ]; then
            echo "Coverage below threshold ($COVERAGE%), failing build."
            exit 1
          fi
